# Generated by Django 5.2.2 on 2025-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count_pages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default=1, upload_to='book-file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='publish_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='publishing_house',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='foto',
            field=models.ImageField(upload_to='book-foto'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(),
        ),
    ]
